config/routes.rb
RandomEtsy::Application.routes.draw do

  root 'products#Art'
  match '/categories',    to: 'categories#list',            via: 'get' 
  match '/Woodworking',   to: 'products#Woodworking',       via: 'get'
  match '/Jewelry',           to: 'products#Jewelry',       via: 'get'
  match '/Pets',           to: 'products#Pets',             via: 'get'
  match '/Art',           to: 'products#Art',               via: 'get'
  match '/Toys',           to: 'products#Toys',             via: 'get'
  match '/Accessories',        to: 'products#Accessories',  via: 'get' 
  match '/contact',       to: 'static_pages#contact',       via: 'get'
  match '/about',         to: 'static_pages#about',         via: 'get'
  match '/ads',           to: 'static_pages#advertisement',  via: 'get'
  match '/Kids',          to: 'products#Kids',              via: 'get'

end

app/views/layouts/_footer.html.erb
<div id="footer">
      <div class="container">
        <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-55135040-1', 'auto');
	  ga('send', 'pageview');
	</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <span class="navbar-brand"> <a href="/"><img src="assets/logo-dcc0ac7a5b41d68ed1e07a0080e4ad99.png"></a></span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right col-lg-0" >
        <% @Cats.each do |i| %>
			<li><a href="<%= i %>"> <%= i %></a></li>
		<% end -%>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_prodCell.html.erb
<div class="row">
	<div id="desc_left" class="col-md-2">
		<div class="side_col">
			
			<div id="next" class="col-sm-12">
				NEXT
			</div>
			<div id="current" class="col-sm-0">
				<h2><%= $current %></h2>
			</div>
			<div id="categories" class="col-sm-0">
				<div id="catHead">
					Categories
				</div>
				<ul>
					<% @Cats.each do |i| %>
						<li><a href="<%= i %>"> <%= i %></a></li>
					<% end -%>
				</ul>
			</div>
		</div>
	</div>
	<div id="desc_page" class="col-sm-12 col-md-8">	
		<div class="col-xs-12 wht">
			<div class="row">
				<div id="desc_content"  class="col-xs-12">
					<img id="bigimg" src="<%= $bigImageP %>" width="100%"  data-image="1" />
					<div id="imgswitch">
						<div class="left" id="<%= $img_total %>">
						</div>
						<div class="right" id="<%= $img_total %>">
						</div>
					</div>
					<div id="multiimages" class="col-xs-12">	
						<% x = 0 %>
						<% @images.each do |i| %>
							<img src="<%= i %>" width="10%" class="<%= x += 1 %>">
						<%end%>
					</div>
				</div>
				<div class="col-xs-12 ">
					<h1 ><%=h $title.html_safe %></h1>
					<p id="price">$<%= $price %></p>
				</div>
			</div>
			<div class="panel panel-default">
			    <div class="panel-heading">
			      <h3 class="panel-title">Description</h3> 
			    </div>
			    <div class="panel-body">
			     <p><%= $description.html_safe %></p>
			    </div>
			</div>
			<div id="view_etsy">
				<%= link_to "View on Etsy", $linky, :target => "_blank" %>
			</div>
		</div>
		
	</div>
	<div id="desc_right" class="col-sm-12 col-md-2">
		<div class="side_col">
			<div class="col-xs-12 front_ad ">	  
				<div class="addImg">				
						<a href="<%= $firstLink %>" target="_blank"><img src="<%= $firstImg %>" border="0" ></a>
				</div>
				<div >
					<p>
						<a href="<%= $firstLink %>" target="_blank"><%= $firstTitle.html_safe %></a>
					</p>
				</div>
			</div>
			<div class="col-xs-12 front_ad">	  
				<div class="addImg">
						<a href="<%= $lastLink %>" target="_blank"><img src="<%= $lastImg %>" border="0" ></a>
				</div>
				<div>
					<p>
						<a href="<%= $lastLink %>" target="_blank"><%= $lastTitle.html_safe %></a>
					</p>
				</div>
			</div>
			<div id="SP" class="col-xs-12">
				<%=  link_to 'Advertise', ads_path %>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
		
	$("#test").click(function(){
		$("#MTop").attr('class', 'gh-svg menu-top menu-ani-top');
		
	});

	$("#next").click(function(){
		location.reload()
	})
	$('h3').click(function(){
		$('.panel-body').slideToggle()
	})
	
	$('#multiimages').children('img').click(function(){
		current = $(this).attr('class')
		$('#bigimg').attr('src', ($(this).attr('src')))
		$('#bigimg').data('image', current)
	})
	$('.right').click(function(){
		img_total = $(this).attr('id');
		img = $('#bigimg').data('image')
		if(img == img_total){
			img = 1
		}
		else{
			img ++
		}
		
		$('#bigimg').data('image',img)
		$('#bigimg').attr('src', $('.'+img).attr('src'))
	})
	$('.left').click(function(){
		img_total = $(this).attr('id');
		img = $('#bigimg').data('image')
		if(img == 1){
			img = img_total
		}
		else{
			img --
		}
		$('#bigimg').data('image',img)
		$('#bigimg').attr('src', $('.'+img).attr('src'))
	})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
</body>
</html>